検索ページのスタイル修正
aspidajs/resthub pull request #17
Opened 2020-01-20 17:07 UTC by lilycoco

## Types of changes

What kind of change does this PR introduce? (check at least one)

- [ ] Breaking change
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactoring
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Description

Issue Number: #5 

まだレスポンシブ対応など出来ていませんが、現状のスタイルを整えました

- `SideBar` コンポーネント作成

- `Buttons.vue` → `Pagenation.vue` へ変更

- `Header` ,  `Footer` コンポーネントは `layouts/default.vue` へ移動

- search ボタン削除 - 入力後一定時間後に検索を実施

- 各企業ロゴ、aspidaロゴの挿入

- その他スタイルの修正 - atom単位のもの(?)はvuetify使いました

<img width="1438" alt="Screen Shot 0002-01-21 at 1 50 11" src="https://user-images.githubusercontent.com/42709317/72744946-ee561f00-3bf1-11ea-8052-8af94dd255dc.png">
<img width="1434" alt="Screen Shot 0002-01-21 at 2 01 59" src="https://user-images.githubusercontent.com/42709317/72745008-12196500-3bf2-11ea-952f-1520033e62f0.png">

2020-01-20 23:36 UTC, hideto2112 requested changes
質問や修正依頼をコメントしたので、確認お願いします。

2020-01-20 23:36 UTC, hideto2112 commented on client/components/Pagenation.vue
> +></template>
改行位置を以下のようにしてください
```vue
  <v-pagination v-model="page" :length="15" :total-visible="4" />
</template>
```

2020-01-20 23:36 UTC, hideto2112 commented on client/components/Pagenation.vue
> -  </div>
下のStyleも、もう使わないようであれば、削除してください。
```vue
<style scoped>
.buttons {
  display: flex;
  flex-direction: row;
  text-align: center;
}
.buttons button {
  width: 25px;
  height: 25px;
  border-radius: 3px;
}
</style>
```

2020-01-20 23:36 UTC, hideto2112 commented on client/components/Pagenation.vue
> +></template>
`page` が定義されていないので、仮でも何か定義しておいた方が良いかと思います。

2020-01-20 23:36 UTC, hideto2112 commented on client/components/Pagenation.vue
>  <template>
v-paginationをラップしていますが、Pagenationというファイル名は意図したものですか？

2020-01-20 23:36 UTC, hideto2112 commented on client/pages/search.vue
> +        ></v-text-field>
タグの間に何も入らないのであれば、以下のように記載してください。
```vue
<v-text-field
/>
```

2020-01-20 23:36 UTC, hideto2112 commented on client/components/Card.vue
> +} */
ここも含めコメントアウトされているStyleは、将来対応用ですか？

2020-01-21 10:59 UTC, lilycoco commented on client/components/Pagenation.vue
>  <template>
typoですすみません🙇‍♀️

2020-01-21 11:03 UTC, lilycoco commented on client/components/Card.vue
> +} */
将来対応予定ですが、今時点で必要ないので削除します！

2020-01-21 12:12 UTC, lilycoco commented
@hideto2112 修正したので再度ご確認お願いします！

2020-01-21 15:58 UTC, hideto2112 approved these changes
指摘箇所が修正されていることを確認しました。

2020-01-23 05:07 UTC, merged

2020-01-23 05:23 UTC, maccostar commented
マージしました！ご対応ありがとうございました。
私が作成したものよりスッキリしてて素晴らしいですー！

色々学ぶことは多かったですが、
一番はpositionがちゃんと理解できていないんだなぁ...とよくわかりました。

---
最後に、次開発する際に検討したいことを備忘として記載します。
- 検討対象
    - SideBar.vueにProp経由送っているapilist
    - SideBar.vue内のgetter(get uniqueCategories)
- 検討内容
今後categoriesをクリックした際の動作をふまえると、
seach.vue内unique化してcategoriesをSideBar.vueに送るのがよいかもしれません。
(categoriesクリック→apilist更新(抽出)→categoriesを再生成...という動きを検討しないと、現時点ではなんとも言いかねますが...)