feature: Add search functions
aspidajs/resthub pull request #18
Opened 2020-02-01 06:27 UTC by shokorep

## Types of changes

What kind of change does this PR introduce? (check at least one)

- [ ] Breaking change
- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactoring
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Description

Issue Number: N/A

### apilist.json
- 検索のプレフィックスに合わせて物理名を変更
　- apiName→service

### 検索機能
#### 仕様
- [service:] のプレフィックス→apilist.service名を検索
- [owner:] のプレフィックス→apilist.onwer名を検索
- 検索は部分一致
- ownerとserviceの両方が入力された場合、and条件で検索結果を返す
- 初期状態及びblankで検索した場合、apilistの全件を返す

## FutureTODO
- プレフィックス無しで検索ワードが入力された時の挙動の検討
- プレフィックスのオートコンプリート実装

## スクリーンショット
![service owner入力](https://user-images.githubusercontent.com/38553438/73588022-f887ef80-4506-11ea-958c-5110fa579a20.png)
![Ownerのみ入力](https://user-images.githubusercontent.com/38553438/73588024-fd4ca380-4506-11ea-9028-6b454008b3b3.png)
![serviceのみ入力](https://user-images.githubusercontent.com/38553438/73588026-00479400-4507-11ea-8c32-6de3508a9da4.png)

2020-02-03 08:51 UTC, hideto2112 submitted a review, later dismissed

2020-02-03 08:51 UTC, hideto2112 commented on client/pages/search.vue
> +      const end: number = this.keyword.length
型推論に任せても良いかと思います。

2020-02-03 08:51 UTC, hideto2112 commented on client/pages/search.vue
> +  }
`st`だと分かりづらいので、`start`くらいであれば、略さなくても良いと思いました。

2020-02-03 08:51 UTC, hideto2112 commented on client/pages/search.vue
> +    } = { service: '', owner: '' }
型推論に任せて良いと思います。

2020-02-03 08:51 UTC, hideto2112 commented on client/pages/search.vue
> +      const bgnOwner: number = this.keyword.indexOf(this.searchKey[1])
ただの質問ですが、`bgn`は何かの略ですか？

2020-02-03 08:51 UTC, hideto2112 commented on client/pages/search.vue
> +
```js
this.keyword.match(this.searchKey[0])
```
を使わずに
下の処理で使っている
```js
this.keyword.indexOf(this.searchKey[0])
```
を使って処理をまとめられませんか？

2020-02-03 08:56 UTC, hideto2112 requested changes
コメント内容の対応をお願いします。

2020-02-03 09:00 UTC, hideto2112 commented on client/pages/search.vue
> +  searchKey: string[] = ['service:', 'owner:']
型推論に任せて良いと思います。

2020-02-03 10:49 UTC, shokorep commented
レビューありがとうございます！
https://github.com/aspidajs/resthub/pull/18/commits/74b9b894aa1c262746cd4fcaca0cdd9c2bb21210
こちらのコミットで指摘の取り込みをいたしました！



また。以下コミットでfutureTODOとしていた、
プレフィックス無しで検索ワードが入力された時の挙動
を実装しました。
https://github.com/aspidajs/resthub/pull/18/commits/0995d094b3cb80763a00b57f3c1654288f5dca46
こちらも見ていただけると大変ありがたいです。。
#### 仕様
- prefixなしで検索された場合はapilist.json のservice及びownerをor検索

2020-02-05 07:28 UTC, shokorep commented
すみません、Changes requestを対応済にしたかったのですが、
やり方がいまいち分からず誤操作しました。。
レビューのプッシュではないので、お手隙で問題ないです！
すみません。。

2020-02-05 22:42 UTC, hideto2112 requested changes
すみません。
1回目で指摘しきれていなかったこともコメント入れてしまいました。
確認をお願いいたします。

2020-02-05 22:42 UTC, hideto2112 commented on client/pages/search.vue
> +      } else if (
```js
if (searchWords.other) {
```
の中身ですが、if文が1つだけなので、まとめられないでしょうか？

2020-02-05 22:42 UTC, hideto2112 commented on client/pages/search.vue
> +        searchWords.owner = this.pickWord(startOwner + 6, startService)
```js
startService + 8
startOwner + 6
```
は3回出ているので、定義しても良いかもしれません。
あと、8と6は数えていると思いますが、searchKeyの文字列の長さを取得する書き方にした方が可読性が上がるかと思いました。

2020-02-05 22:42 UTC, hideto2112 commented on client/pages/search.vue
> +  searchKey = ['service:', 'owner:']
もし、他から参照する予定がなければ、`search()`の中で定義しても良いかと思ったのですが、何かに使いそうですか？

2020-02-05 22:42 UTC, hideto2112 commented on client/pages/search.vue
> +  }
ゲッターで書いてください。
```js
get pickWord() {
  ...
}
```

2020-02-05 22:42 UTC, hideto2112 commented on client/pages/search.vue
> +    this.searchedApilist = JSON.parse(JSON.stringify(this.apilist))
`created()`では
```ts
this.searchedApilist = this.apilist
```
となっていますが、ここでは`JSON.parse` `JSON.stringify` を使っている意図はなんでしょうか？
もし同じ処理ならリセットする関数を作って、呼び出しても良いかと思います。

2020-02-07 06:04 UTC, shokorep commented on client/pages/search.vue
> +  searchKey = ['service:', 'owner:']
後々、このprefixはサジェストされるようにしたいので外出ししていましたが、
実装するタイミングでcontant.tsにまとめるなど、やり方は考えたいと思います。
一旦search()に入れました。

2020-02-07 06:09 UTC, shokorep commented
レビューありがとうございます！
指摘事項修正しました！

2020-02-10 10:07 UTC, hideto2112 approved these changes
ご対応ありがとうございます。

2020-02-10 10:08 UTC, merged