Feat: Filter Categories
aspidajs/resthub pull request #32
Opened 2020-02-24 14:13 UTC by lilycoco

## Types of changes

What kind of change does this PR introduce? (check at least one)

- [ ] Breaking change
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactoring
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Description

Issue Number: N/A

@hi85gh 
Filterの機能を追加しました。
ご確認お願いします！

2020-03-02 09:56 UTC, hideto2112 requested changes
SideBarコンポーネントだけコメント書きました。確認をお願いします。

2020-03-02 09:56 UTC, hideto2112 commented on client/components/SideBar.vue
> +  @Emit('input')
emitで親に渡す関数名と子の関数名が同一の時は`@Emit()`のようにカッコ内を省略できます。

2020-03-02 09:56 UTC, hideto2112 commented on client/components/SideBar.vue
> +    this.input(this.selectedItems)
アクセス修飾子ですが、以下の理由で付けないで良いと思います。
- プロジェクト内の統一
TSを使っているほかのVueファイルは、アクセス修飾子を付けていない。
- アクセス修飾子の有効性
コンポーネント内の関数をほかのコンポーネントから呼んでしまうと、どこから呼ばれているのか把握が難しくなるため、好ましくなく外部から呼ばないのでアクセス修飾子を付けて利用する機会が基本的にはない。
また、以下の記事を読んでみると、アクセス修飾子を付けてもトランスパイル時に無視されてしまうようなので、そもそも意味を成さないかもとの記述もあります。
参考）[](https://rennnosukesann.hatenablog.com/entry/2019/09/14/113614)

2020-03-08 08:14 UTC, lilycoco commented
@hideto2112 
レビューありがとうございます！

修正したので再度確認お願いします🙏

2020-03-08 09:09 UTC, hideto2112 approved these changes
修正確認しました。ありがとうございます。

2020-03-08 09:10 UTC, merged