Bug Fix: Fix filers order
aspidajs/resthub pull request #49
Opened 2020-03-20 04:26 UTC by lilycoco

## Types of changes

What kind of change does this PR introduce? (check at least one)

- [ ] Breaking change
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactoring
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Description
Filter の並び順がバラバラだったので、ソートをかけました。
デフォルトではアルファベットの大文字が先に来てしまうので、大文字小文字関係なく並べてます。

**Before**
<img width="235" alt="Screen Shot 0002-03-20 at 13 25 27" src="https://user-images.githubusercontent.com/42709317/77135535-4607ee00-6aae-11ea-8c4e-a4b820486247.png">

**After**
<img width="251" alt="Screen Shot 0002-03-20 at 13 23 17" src="https://user-images.githubusercontent.com/42709317/77135248-f9bcae00-6aad-11ea-8a2f-735a7e12c1f5.png">

Issue Number: N/A

2020-03-20 15:46 UTC, hideto2112 requested changes
型が一箇所合っていないので修正をお願いします。

2020-03-20 15:46 UTC, hideto2112 commented on client/components/SideBar.vue
> +  @Prop({ type: Array, required: true }) categories!: Record<string, number>
正しく認識されずエラーが出ないのですが
```ts
categories!: Record<string, number>
```
は
```ts
categories!: { [key: string]: number }
```
という型を表し、受け取っているものと型が異なるので、以下のように書き換えてください。
```ts
categories!: [string, number][]
```

2020-03-23 10:55 UTC, lilycoco commented on client/components/SideBar.vue
> +  @Prop({ type: Array, required: true }) categories!: Record<string, number>
@hideto2112 なるほど型の読み方良く分かってなかったです。。ありがとうございます！
修正したので確認お願いします！

2020-03-30 06:21 UTC, hideto2112 approved these changes
修正いただき、ありがとうございます。

2020-03-30 06:22 UTC, merged