[Style Improvement] Fix style of Api list on apiService page
aspidajs/resthub pull request #73
Opened 2020-04-27 16:15 UTC by lilycoco

## Types of changes

What kind of change does this PR introduce? (check at least one)

- [ ] Breaking change
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactoring
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Description
API list のスタイルを整えて、`method`の色を追加しました。
200行ルールに引っかかってしまったので`method`の色を`util`に分けてます。

### Before

<img width="1427" alt="Screen Shot 0002-04-28 at 1 09 21" src="https://user-images.githubusercontent.com/42709317/80394748-41282c80-88ed-11ea-80ed-29a6bd7fcf3d.png">

### After

<img width="1434" alt="Screen Shot 0002-04-28 at 1 06 22" src="https://user-images.githubusercontent.com/42709317/80394761-471e0d80-88ed-11ea-8d3b-3a48e3b24937.png">

Issue Number: N/A

2020-04-29 11:01 UTC, hideto2112 requested changes
3箇所コメントしました。ご確認をお願いします。

2020-04-29 11:01 UTC, hideto2112 commented on client/utils/methodColors.js
> +}
今後定数が増えることもありそうなので、`utils/constants.ts`などにして、以下のように定義してはどうかと思います。
```ts
export const METHOD_COLORS = {
   ...
}
```

2020-04-29 11:01 UTC, hideto2112 commented on client/components/pages/apiService/ApiMethod.vue
> +import methodColors from '../../../utils/methodColors.js'
ほかのコンポーネントと合わせて、`~`を使って書いていただけたらと思います。
あと、`.js`と`.ts`の部分は省略しても大丈夫です。
```js
import methodColors from '~/utils/methodColors'
```

2020-04-29 11:01 UTC, hideto2112 commented on client/components/pages/apiService/ApiSideBar.vue
> +import methodColors from '../../../utils/methodColors.js'
`client/components/pages/apiService/ApiMethod.vue`と同様でお願いします。

2020-04-29 13:39 UTC, lilycoco commented
修正しました。ご確認お願いします！

2020-04-30 01:43 UTC, hideto2112 approved these changes
修正ありがとうございます。確認しました。

2020-04-30 01:43 UTC, merged